name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y libfl-dev flex bison
      - uses: actions/checkout@v3
      - name: make
        run: make
      - name: make test
        run: make test
